/* DO NOT EDIT THIS FILE - it is machine generated */
//LINUX

#include <jni.h>
// #include "/usr/lib/gcc/i386-redhat-linux/3.4.3/include/jni.h"
//#include "/opt/jdk1.5/include/jni.h"
//#include "/usr/java/jdk1.6.0_13/include/jni.h"
// MAC  #include"/System/Library/Frameworks/JavaVM.framework/Headers/jni.h"

/* Header for class elkfed_ml_svm_SVMLightTK */

#ifndef _Included_elkfed_ml_svm_SVMLightTK
#define _Included_elkfed_ml_svm_SVMLightTK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:    IBM_svm_SVMLightTK
 * Method:    load_model
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_IBM_svm_SVMLightTK_load_1model
  (JNIEnv *, jclass, jstring);

/*
 * Class:     IBM_svm_SVMLightTK
 * Method:    get_threshold
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_IBM_svm_SVMLightTK_get_1threshold
  (JNIEnv *, jclass);

/*
 * Class:     IBM_svm_SVMLightTK
 * Method:    classify_instance
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_IBM_svm_SVMLightTK_classify_1instance
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
